- name: Install necessary package
  apt: 
      name: apt-transport-https
      state: present
      update_cache: yes

- name: add grafana gpg key
  shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

- name: add grafana repo 
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Install grafana
  apt: 
      name: grafana
      state: present
      update_cache: yes

- name: "Grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "Grafana server started"
  service:
    name: grafana-server
    enabled: true
    state: started

- name: "Check if Grafana is accessible."
  uri:
    url: http://localhost:3000
    method: GET
    status_code: 200

- name: Import alert manager
  community.grafana.grafana_dashboard:
    grafana_url: http://localhost:3000
    grafana_api_key: "{{ grafana_api_key }}"
    folder: General
    overwrite: yes
    dashboard_url: https://raw.githubusercontent.com/PauloGDPeixoto/ctw-academy/main/resources/alertmanager_rev4.json

- name: Import node exporter
  community.grafana.grafana_dashboard:
    grafana_url: http://localhost:3000
    grafana_api_key: "{{ grafana_api_key }}"
    folder: General
    overwrite: yes
    dashboard_url: https://raw.githubusercontent.com/PauloGDPeixoto/ctw-academy/main/resources/node-exporter-server-metrics_rev8.json

- name: Import prometheus
  community.grafana.grafana_dashboard:
    grafana_url: http://localhost:3000
    grafana_api_key: "{{ grafana_api_key }}"
    folder: General
    overwrite: yes
    dashboard_url: https://raw.githubusercontent.com/PauloGDPeixoto/ctw-academy/main/resources/prometheus-2-0-overview_rev2.json